name: rcs-rw-10-filip
root: ~/

aliases:
  - &app_command "timeout 60m java -Dspring.profiles.active=Random-Walker,remote -jar rain-cloud-system-1.0.0-exec.jar --spring.config.location=application.properties"

windows:
  - strong-nodes:
      layout: tiled
      synchronize: after
      panes:
        - s1-2:
            - ssh -o StrictHostKeyChecking=no s1-2
            - *app_command
        - s2-2:
            - ssh -o StrictHostKeyChecking=no s2-2
            - *app_command
  - medium-nodes:
      layout: tiled
      synchronize: after
      panes:
        - m1-2:
            - ssh -o StrictHostKeyChecking=no m1-2
            - *app_command
        - m2-2:
            - ssh -o StrictHostKeyChecking=no m2-2
            - *app_command
        - m3-2:
            - ssh -o StrictHostKeyChecking=no m3-2
            - *app_command
  - weak-nodes:
      layout: tiled
      synchronize: after
      panes:
        - w1-2:
            - ssh -o StrictHostKeyChecking=no w1-2
            - *app_command
        - w2-2:
            - ssh -o StrictHostKeyChecking=no w2-2
            - *app_command
        - w3-2:
            - ssh -o StrictHostKeyChecking=no w3-2
            - *app_command
        - w4-2:
            - ssh -o StrictHostKeyChecking=no w4-2
            - *app_command
        - w5-2:
            - ssh -o StrictHostKeyChecking=no w5-2
            - *app_command
