name: rcs-gossips-10-filip
root: ~/

aliases:
  - &app_command "timeout 60m java -Dspring.profiles.active=Gossips,remote -jar rain-cloud-system-1.0.0-exec.jar --spring.config.location=application.properties"

windows:
  - strong-nodes:
      layout: tiled
      synchronize: after
      panes:
        - s1-6:
            - ssh -o StrictHostKeyChecking=no s1-6
            - *app_command
        - s2-6:
            - ssh -o StrictHostKeyChecking=no s2-6
            - *app_command
  - medium-nodes:
      layout: tiled
      synchronize: after
      panes:
        - m1-6:
            - ssh -o StrictHostKeyChecking=no m1-6
            - *app_command
        - m2-6:
            - ssh -o StrictHostKeyChecking=no m2-6
            - *app_command
        - m3-6:
            - ssh -o StrictHostKeyChecking=no m3-6
            - *app_command
  - weak-nodes:
      layout: tiled
      synchronize: after
      panes:
        - w1-6:
            - ssh -o StrictHostKeyChecking=no w1-6
            - *app_command
        - w2-6:
            - ssh -o StrictHostKeyChecking=no w2-6
            - *app_command
        - w3-6:
            - ssh -o StrictHostKeyChecking=no w3-6
            - *app_command
        - w4-6:
            - ssh -o StrictHostKeyChecking=no w4-6
            - *app_command
        - w5-6:
            - ssh -o StrictHostKeyChecking=no w5-6
            - *app_command
