name: rcs-gossips-100-worse
root: ~/

aliases:
  - &app_command "timeout 60m java -Dspring.profiles.active=Gossips,remote -jar rain-cloud-system-1.0.0-exec.jar --spring.config.location=application.properties"

windows:
  - strong-nodes-s1-1-5:
      layout: tiled
      synchronize: after
      panes:
        - s1-1:
            - ssh -o StrictHostKeyChecking=no s1-1
            - *app_command
        - s1-2:
            - ssh -o StrictHostKeyChecking=no s1-2
            - *app_command
        - s1-3:
            - ssh -o StrictHostKeyChecking=no s1-3
            - *app_command
        - s1-4:
            - ssh -o StrictHostKeyChecking=no s1-4
            - *app_command
        - s1-5:
            - ssh -o StrictHostKeyChecking=no s1-5
            - *app_command
  - strong-nodes-s1-6-10:
      layout: tiled
      synchronize: after
      panes:
        - s1-6:
            - ssh -o StrictHostKeyChecking=no s1-6
            - *app_command
        - s1-7:
            - ssh -o StrictHostKeyChecking=no s1-7
            - *app_command
        - s1-8:
            - ssh -o StrictHostKeyChecking=no s1-8
            - *app_command
        - s1-9:
            - ssh -o StrictHostKeyChecking=no s1-9
            - *app_command
        - s1-10:
            - ssh -o StrictHostKeyChecking=no s1-10
            - *app_command
  - strong-nodes-s2-1-5:
      layout: tiled
      synchronize: after
      panes:
        - s2-1:
            - ssh -o StrictHostKeyChecking=no s2-1
            - *app_command
        - s2-2:
            - ssh -o StrictHostKeyChecking=no s2-2
            - *app_command
        - s2-3:
            - ssh -o StrictHostKeyChecking=no s2-3
            - *app_command
        - s2-4:
            - ssh -o StrictHostKeyChecking=no s2-4
            - *app_command
        - s2-5:
            - ssh -o StrictHostKeyChecking=no s2-5
            - *app_command
  - strong-nodes-s2-6-10:
      layout: tiled
      synchronize: after
      panes:
        - s2-6:
            - ssh -o StrictHostKeyChecking=no s2-6
            - *app_command
        - s2-7:
            - ssh -o StrictHostKeyChecking=no s2-7
            - *app_command
        - s2-8:
            - ssh -o StrictHostKeyChecking=no s2-8
            - *app_command
        - s2-9:
            - ssh -o StrictHostKeyChecking=no s2-9
            - *app_command
        - s2-10:
            - ssh -o StrictHostKeyChecking=no s2-10
            - *app_command
  - medium-nodes-m1-1-5:
      layout: tiled
      synchronize: after
      panes:
        - m1-1:
            - ssh -o StrictHostKeyChecking=no m1-1
            - *app_command
        - m1-2:
            - ssh -o StrictHostKeyChecking=no m1-2
            - *app_command
        - m1-3:
            - ssh -o StrictHostKeyChecking=no m1-3
            - *app_command
        - m1-4:
            - ssh -o StrictHostKeyChecking=no m1-4
            - *app_command
        - m1-5:
            - ssh -o StrictHostKeyChecking=no m1-5
            - *app_command
  - medium-nodes-m1-6-10:
      layout: tiled
      synchronize: after
      panes:
        - m1-6:
            - ssh -o StrictHostKeyChecking=no m1-6
            - *app_command
        - m1-7:
            - ssh -o StrictHostKeyChecking=no m1-7
            - *app_command
        - m1-8:
            - ssh -o StrictHostKeyChecking=no m1-8
            - *app_command
        - m1-9:
            - ssh -o StrictHostKeyChecking=no m1-9
            - *app_command
        - m1-10:
            - ssh -o StrictHostKeyChecking=no m1-10
            - *app_command
  - medium-nodes-m2-1-5:
      layout: tiled
      synchronize: after
      panes:
        - m2-1:
            - ssh -o StrictHostKeyChecking=no m2-1
            - *app_command
        - m2-2:
            - ssh -o StrictHostKeyChecking=no m2-2
            - *app_command
        - m2-3:
            - ssh -o StrictHostKeyChecking=no m2-3
            - *app_command
        - m2-4:
            - ssh -o StrictHostKeyChecking=no m2-4
            - *app_command
        - m2-5:
            - ssh -o StrictHostKeyChecking=no m2-5
            - *app_command
  - medium-nodes-m2-6-10:
      layout: tiled
      synchronize: after
      panes:
        - m2-6:
            - ssh -o StrictHostKeyChecking=no m2-6
            - *app_command
        - m2-7:
            - ssh -o StrictHostKeyChecking=no m2-7
            - *app_command
        - m2-8:
            - ssh -o StrictHostKeyChecking=no m2-8
            - *app_command
        - m2-9:
            - ssh -o StrictHostKeyChecking=no m2-9
            - *app_command
        - m2-10:
            - ssh -o StrictHostKeyChecking=no m2-10
            - *app_command
  - medium-nodes-m3-1-5:
      layout: tiled
      synchronize: after
      panes:
        - m3-1:
            - ssh -o StrictHostKeyChecking=no m3-1
            - *app_command
        - m3-2:
            - ssh -o StrictHostKeyChecking=no m3-2
            - *app_command
        - m3-3:
            - ssh -o StrictHostKeyChecking=no m3-3
            - *app_command
        - m3-4:
            - ssh -o StrictHostKeyChecking=no m3-4
            - *app_command
        - m3-5:
            - ssh -o StrictHostKeyChecking=no m3-5
            - *app_command
  - medium-nodes-m3-6-10:
      layout: tiled
      synchronize: after
      panes:
        - m3-6:
            - ssh -o StrictHostKeyChecking=no m3-6
            - *app_command
        - m3-7:
            - ssh -o StrictHostKeyChecking=no m3-7
            - *app_command
        - m3-8:
            - ssh -o StrictHostKeyChecking=no m3-8
            - *app_command
        - m3-9:
            - ssh -o StrictHostKeyChecking=no m3-9
            - *app_command
        - m3-10:
            - ssh -o StrictHostKeyChecking=no m3-10
            - *app_command
  - weak-nodes-w1-1-5:
      layout: tiled
      synchronize: after
      panes:
        - w1-1:
            - ssh -o StrictHostKeyChecking=no w1-1
            - *app_command
        - w1-2:
            - ssh -o StrictHostKeyChecking=no w1-2
            - *app_command
        - w1-3:
            - ssh -o StrictHostKeyChecking=no w1-3
            - *app_command
        - w1-4:
            - ssh -o StrictHostKeyChecking=no w1-4
            - *app_command
        - w1-5:
            - ssh -o StrictHostKeyChecking=no w1-5
            - *app_command
  - weak-nodes-w1-6-10:
      layout: tiled
      synchronize: after
      panes:
        - w1-6:
            - ssh -o StrictHostKeyChecking=no w1-6
            - *app_command
        - w1-7:
            - ssh -o StrictHostKeyChecking=no w1-7
            - *app_command
        - w1-8:
            - ssh -o StrictHostKeyChecking=no w1-8
            - *app_command
        - w1-9:
            - ssh -o StrictHostKeyChecking=no w1-9
            - *app_command
        - w1-10:
            - ssh -o StrictHostKeyChecking=no w1-10
            - *app_command
  - weak-nodes-w2-1-5:
      layout: tiled
      synchronize: after
      panes:
        - w2-1:
            - ssh -o StrictHostKeyChecking=no w2-1
            - *app_command
        - w2-2:
            - ssh -o StrictHostKeyChecking=no w2-2
            - *app_command
        - w2-3:
            - ssh -o StrictHostKeyChecking=no w2-3
            - *app_command
        - w2-4:
            - ssh -o StrictHostKeyChecking=no w2-4
            - *app_command
        - w2-5:
            - ssh -o StrictHostKeyChecking=no w2-5
            - *app_command
  - weak-nodes-w2-6-10:
      layout: tiled
      synchronize: after
      panes:
        - w2-6:
            - ssh -o StrictHostKeyChecking=no w2-6
            - *app_command
        - w2-7:
            - ssh -o StrictHostKeyChecking=no w2-7
            - *app_command
        - w2-8:
            - ssh -o StrictHostKeyChecking=no w2-8
            - *app_command
        - w2-9:
            - ssh -o StrictHostKeyChecking=no w2-9
            - *app_command
        - w2-10:
            - ssh -o StrictHostKeyChecking=no w2-10
            - *app_command
  - weak-nodes-w3-1-5:
      layout: tiled
      synchronize: after
      panes:
        - w3-1:
            - ssh -o StrictHostKeyChecking=no w3-1
            - *app_command
        - w3-2:
            - ssh -o StrictHostKeyChecking=no w3-2
            - *app_command
        - w3-3:
            - ssh -o StrictHostKeyChecking=no w3-3
            - *app_command
        - w3-4:
            - ssh -o StrictHostKeyChecking=no w3-4
            - *app_command
        - w3-5:
            - ssh -o StrictHostKeyChecking=no w3-5
            - *app_command
  - weak-nodes-w3-6-10:
      layout: tiled
      synchronize: after
      panes:
        - w3-6:
            - ssh -o StrictHostKeyChecking=no w3-6
            - *app_command
        - w3-7:
            - ssh -o StrictHostKeyChecking=no w3-7
            - *app_command
        - w3-8:
            - ssh -o StrictHostKeyChecking=no w3-8
            - *app_command
        - w3-9:
            - ssh -o StrictHostKeyChecking=no w3-9
            - *app_command
        - w3-10:
            - ssh -o StrictHostKeyChecking=no w3-10
            - *app_command
  - weak-nodes-w4-1-5:
      layout: tiled
      synchronize: after
      panes:
        - w4-1:
            - ssh -o StrictHostKeyChecking=no w4-1
            - *app_command
        - w4-2:
            - ssh -o StrictHostKeyChecking=no w4-2
            - *app_command
        - w4-3:
            - ssh -o StrictHostKeyChecking=no w4-3
            - *app_command
        - w4-4:
            - ssh -o StrictHostKeyChecking=no w4-4
            - *app_command
        - w4-5:
            - ssh -o StrictHostKeyChecking=no w4-5
            - *app_command
  - weak-nodes-w4-6-10:
      layout: tiled
      synchronize: after
      panes:
        - w4-6:
            - ssh -o StrictHostKeyChecking=no w4-6
            - *app_command
        - w4-7:
            - ssh -o StrictHostKeyChecking=no w4-7
            - *app_command
        - w4-8:
            - ssh -o StrictHostKeyChecking=no w4-8
            - *app_command
        - w4-9:
            - ssh -o StrictHostKeyChecking=no w4-9
            - *app_command
        - w4-10:
            - ssh -o StrictHostKeyChecking=no w4-10
            - *app_command
  - weak-nodes-w5-1-5:
      layout: tiled
      synchronize: after
      panes:
        - w5-1:
            - ssh -o StrictHostKeyChecking=no w5-1
            - *app_command
        - w5-2:
            - ssh -o StrictHostKeyChecking=no w5-2
            - *app_command
        - w5-3:
            - ssh -o StrictHostKeyChecking=no w5-3
            - *app_command
        - w5-4:
            - ssh -o StrictHostKeyChecking=no w5-4
            - *app_command
        - w5-5:
            - ssh -o StrictHostKeyChecking=no w5-5
            - *app_command
  - weak-nodes-w5-6-10:
      layout: tiled
      synchronize: after
      panes:
        - w5-6:
            - ssh -o StrictHostKeyChecking=no w5-6
            - *app_command
        - w5-7:
            - ssh -o StrictHostKeyChecking=no w5-7
            - *app_command
        - w5-8:
            - ssh -o StrictHostKeyChecking=no w5-8
            - *app_command
        - w5-9:
            - ssh -o StrictHostKeyChecking=no w5-9
            - *app_command
        - w5-10:
            - ssh -o StrictHostKeyChecking=no w5-10
            - *app_command
